[package]
name = "rust_leetecode"
version = "0.1.0"
edition = "2021"
authors = ["Zepeng Zhang(a.k.a PeterWright) <peterwrighten@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
